name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    strategy:
      fail-fast: false

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2

    - name: Load modules
      run: |
        module load BuildEnv/gcc-12.2.0.lua

    - name: Build h5pp
      run: |
        mkdir build && cd build && cmake ..
        make -j2 || make -j1 VERBOSE=1

    - name: Test h5pp
      run: |
        cd build
        ctest -j2 --output-on-failure
