name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    strategy:
      fail-fast: false

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2

    - name: Build h5pp
      run: |
        module load BuildEnv/gcc-12.2.0.lua;
        mkdir build && cd build && cmake ..;
        make -j2 || make -j1 VERBOSE=1

    - name: Test h5pp
      env:
        HDF5_USE_FILE_LOCKING: 'FALSE'
      run: |
        module load BuildEnv/gcc-12.2.0.lua;
        cd build;
        ctest -j4 --output-on-failure
